In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
electric_data = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
electric_data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
electric_data.isnull().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [5]:
electric_data = electric_data.drop('stab',axis=1)

In [6]:
electric_data.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = electric_data.drop('stabf',axis=1)
y = electric_data['stabf']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
scaled_X_train = scaler.fit_transform(X_train)

In [13]:
scaled_X_test = scaler.transform(X_test)

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
rfc = RandomForestClassifier()

In [16]:
rfc.fit(scaled_X_train,y_train)

RandomForestClassifier()

In [17]:
rfc_prediction = rfc.predict(scaled_X_test)

In [18]:
from sklearn.metrics import confusion_matrix, classification_report

In [19]:
print(confusion_matrix(y_test,rfc_prediction))
print('\n')
print(classification_report(y_test,rfc_prediction))

[[ 618   94]
 [  60 1228]]


              precision    recall  f1-score   support

      stable       0.91      0.87      0.89       712
    unstable       0.93      0.95      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.91      0.92      2000
weighted avg       0.92      0.92      0.92      2000



In [20]:
from sklearn.ensemble import ExtraTreesClassifier

In [21]:
etc = ExtraTreesClassifier()

In [22]:
etc.fit(scaled_X_train,y_train)

ExtraTreesClassifier()

In [23]:
etc_prediction = etc.predict(scaled_X_test)

In [24]:
print(confusion_matrix(y_test,etc_prediction))
print('\n')
print(classification_report(y_test,etc_prediction))

[[ 599  113]
 [  41 1247]]


              precision    recall  f1-score   support

      stable       0.94      0.84      0.89       712
    unstable       0.92      0.97      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.93      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000



In [25]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [26]:
pip install lightgbm

Note: you may need to restart the kernel to use updated packages.


In [27]:
from xgboost import XGBClassifier

In [28]:
xgb = XGBClassifier()

In [29]:
xgb.fit(scaled_X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [30]:
xgb_prediction = xgb.predict(scaled_X_test)

In [31]:
print(confusion_matrix(y_test,xgb_prediction))
print('\n')
print(classification_report(y_test,xgb_prediction))

[[ 648   64]
 [  45 1243]]


              precision    recall  f1-score   support

      stable       0.94      0.91      0.92       712
    unstable       0.95      0.97      0.96      1288

    accuracy                           0.95      2000
   macro avg       0.94      0.94      0.94      2000
weighted avg       0.95      0.95      0.95      2000



In [32]:
from lightgbm import LGBMClassifier

In [33]:
lgbm = LGBMClassifier()

In [34]:
lgbm.fit(scaled_X_train,y_train)

LGBMClassifier()

In [35]:
lgbm_prediction = lgbm.predict(scaled_X_test)

In [36]:
print(confusion_matrix(y_test,lgbm_prediction))
print('\n')
print(classification_report(y_test,lgbm_prediction))

[[ 635   77]
 [  48 1240]]


              precision    recall  f1-score   support

      stable       0.93      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.94      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



In [37]:
from sklearn.model_selection import RandomizedSearchCV

In [38]:
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None] 

hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}

In [49]:
random_grid = RandomizedSearchCV(ExtraTreesClassifier(),hyperparameter_grid,verbose=1,cv=5,n_iter=10,scoring='accuracy',n_jobs=-1,random_state=1)

In [50]:
random_grid.fit(scaled_X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   19.8s
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:   35.6s finished


RandomizedSearchCV(cv=5, estimator=ExtraTreesClassifier(), n_jobs=-1,
                   param_distributions={'max_features': ['auto', 'sqrt', 'log2',
                                                         None],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 3, 5, 7, 9],
                                        'n_estimators': [50, 100, 300, 500,
                                                         1000]},
                   random_state=1, scoring='accuracy', verbose=1)

In [51]:
random_grid.best_estimator_

ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000)

In [42]:
random_grid_prediction = random_grid.predict(scaled_X_test)

In [52]:
etc1 = ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000)
etc1.fit(scaled_X_train,y_train)

ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000)

In [53]:
etc1_prediction = etc1.predict(scaled_X_test)

print(confusion_matrix(y_test,etc1_prediction))
print('\n')
print(classification_report(y_test,etc1_prediction))

[[ 619   93]
 [  53 1235]]


              precision    recall  f1-score   support

      stable       0.92      0.87      0.89       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [43]:
print(confusion_matrix(y_test,random_grid_prediction))
print('\n')
print(classification_report(y_test,random_grid_prediction))

[[ 634   78]
 [  50 1238]]


              precision    recall  f1-score   support

      stable       0.93      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



In [44]:
from sklearn.metrics import accuracy_score

In [45]:
print('Accuracy : {}'.format(accuracy_score(y_test,random_grid_prediction)))

Accuracy : 0.936


In [46]:
print('Accuracy : {}'.format(accuracy_score(y_test,rfc_prediction)))

Accuracy : 0.923


In [47]:
print('Accuracy : {}'.format(accuracy_score(y_test,xgb_prediction)))

Accuracy : 0.9455


In [48]:
print('Accuracy : {}'.format(accuracy_score(y_test,lgbm_prediction)))

Accuracy : 0.9375


In [55]:
etc.feature_importances_.max()

0.11770724572789153

In [56]:
etc.feature_importances_

array([0.11724596, 0.11770725, 0.11493255, 0.11435653, 0.03987865,
       0.04044851, 0.04092583, 0.04068022, 0.08898532, 0.09417098,
       0.09734355, 0.09332465])

In [57]:
etc.feature_importances_.min()

0.03987865317218443